spring:
  application:
    name: product
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  management:
    tracing:
      sampling:
        probability: 1.0
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans # Zipkin 서버 주소

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  hystrix:
    enabled: true

server:
  port: 19092

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${JWT_SECRET_KEY}