spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: product

server:
  port: 19092

logging:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  hystrix:
    enabled: true