spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: order

server:
  port: 19096

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  hystrix:
    enabled: true