server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/alert/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hub/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}