server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/products/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: ai
          uri: lb://ai
          predicates:
            - Path=/ai/**
        - id: alert
          uri: lb://alert
          predicates:
            - Path=/alert/**
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
        - id: company
          uri: lb://company
          predicates:
            - Path=/company/**
        - id: hub
          uri: lb://hub
          predicates:
            - Path=/hub/**
        - id: users
        - uri: lb://users
        - predicates:
            - Path=/users/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}