spring:
  application:
    name: ai

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/msa_test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent"
    key: ${GEMINI_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19099