spring:
  application:
    name: alert

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true

slack:
  token: ${SLACK_TOKEN}
  chanel-id : ${SLACK_CHANNEL_ID} #  #slackalert

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19010

service:
  jwt:
    access-expiration: 3600000
    secret-key: ${JWT_SECRET_KEY}